### ISSUE TITLE
`OctoRelayPlugin` object has no attribute `model`

### ISSUE THREAD

**Issue by XAMCTBO** [borisbu/OctoRelay#25]
Hi
after latest update is stopped working (octopi  1.6.0)
octopi (updated)
PI updated

log shows
`2021-05-01 15:33:10,480 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2021-05-01 15:33:10,495 - octoprint.plugin - ERROR - Error while calling plugin octorelay
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octorelay/__init__.py", line 220, in on_event
    self.update_ui()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octorelay/__init__.py", line 312, in update_ui
    self.model[index]['iconText'] = iconOn
AttributeError: 'OctoRelayPlugin' object has no attribute 'model'
2021-05-01 15:33:10,687 - octoprint.server.util.flask - INFO - Passively logging in user alex from ::ffff:192.168.1.28`

**Comment by RobinTail** [comment]
The supplied log shows that `on_event` called before `on_after_startup` which sets the `model`.
This issue has most likely been already resolved on September 2021 in this commit:

https://github.com/borisbu/OctoRelay/commit/d9e9f93a37c2cb87104d50047246e88f94f41145#diff-515c8cdc2c54449d864cbd805fc587c8d46e167902e3b462c16925371d0a3c2cR264

Please retry with most recent versions again.
If the issue remains, please create another issue with a similar log.
Thank you, @XAMCTBO
